.TH spongex 1
.SH NAME
spongex \- Used to run open source analytics on your various projects
.SH SYNOPSIS
.B luffax
[\fIOPTIONS\fR] \fICOMMAND\fR [\fIPARAMETERS\fR]
.SH DESCRIPTION
.PP
.B luffax
DOCUMENT THIS
.PP
.B luffax
etc...

.SH AUTHOR
Written by David J. Kordsmeier <dkords@gmail.com>
.SH REPORTING BUGS
Report bugs to 
.I dkords@gmail.com
.SH COPYRIGHT
ADD
.br
PUT LICENSE HERE
.SH SEE ALSO
For the most up to date list of options run 
.B spongex \-\-help
.br
For more info about usage, examples and other related info visit project homepage at
.br
.B http://github.com/truedat101/spongex
